# Loco yaml export: Simple YAML object
# Project: application-dev.properties conversion
# Release: Working copy
# Locale: dev, Domung
# Exported by: Unregistered user
# Exported at: Thu, 21 Mar 2019 17:16:27 +0530
---
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/serviceManagement?createDatabaseIfNotExist=true
spring.datasource.username: root
spring.datasource.password: asdf1234
spring.jpa.database-platform: org.hibernate.dialect.MySQL57Dialect
spring.jpa.show-sql: "true"
spring.jpa.generate-ddl: "true"
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server.port: "8081"
...
